services:

  postgres:    
    image: 'postgres:15-alpine'
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - ~/data/site/psql:/var/lib/postgresql/data/pgdata

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile